# MACHINE LEARNING

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [2]:
heat = pd.read_csv('../data/raw/Heat_Stroke.csv')
heat

,Daily Ingested Water (L),Time of year (month),Cardiovascular disease history,Dehydration,Heat Index (HI),Diastolic BP,Environmental temperature (C),Sickle Cell Trait (SCT),Systolic BP,Weight (kg),...,Heart / Pulse rate (b/min),Age,Sweating,"Skin color (flushed/normal=1, pale=0.5, cyatonic=0)",Strenuous exercise,Nationality,Sex,Hot/dry skin,Time of day,Heat stroke
0,2.821588,7.000000,0,0,107.296910,20.000000,39.000000,0,60.000000,48.364079,...,166.000000,38.000000,0,0.021014,0.500000,1,1,0,10.550628,1
1,5.000000,6.841842,0,0,105.410610,90.000000,37.700000,0,120.000000,52.413863,...,68.000000,50.000000,1,0.045987,0.000000,1,0,0,10.613669,1
2,5.000000,4.636197,0,0,101.823065,50.000000,37.700000,0,100.000000,46.344503,...,96.000000,64.000000,0,0.031299,0.000000,1,0,0,14.419615,1
3,10.500000,2.589828,0,0,95.925389,78.000000,37.700000,0,116.000000,42.132476,...,70.000000,19.000000,0,0.052654,0.000000,1,0,0,9.467515,1
4,5.000000,9.914389,0,0,101.673016,88.000000,37.700000,0,130.000000,41.856694,...,88.000000,21.000000,1,0.076099,0.000000,1,0,0,12.460315,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
604,2.625332,11.808261,0,0,69.444843,82.705255,28.276056,0,117.025213,45.173841,...,106.868166,28.952569,1,0.060595,0.038827,1,1,0,16.994422,0
605,1.069333,7.369952,0,0,67.273039,83.822981,26.008688,0,116.654793,53.125129,...,93.713145,52.733157,1,0.031162,0.657076,0,1,0,12.034963,0
606,1.085594,6.955786,0,0,53.017902,85.101995,32.863125,0,112.713272,47.898687,...,143.858902,21.496651,0,0.015298,0.260901,0,0,0,16.545827,0
607,5.916055,2.741906,0,0,78.665639,88.765944,22.353665,0,111.962413,52.487889,...,181.952819,26.420689,0,0.050419,0.305553,1,0,0,16.757862,0
608,5.654623,2.287122,0,0,77.649841,84.971577,33.082008,0,110.941965,51.229314,...,136.743099,19.029703,0,0.041355,0.808819,0,0,0,14.171093,0

In [3]:
heat.columns

Index(['Daily Ingested Water (L)', 'Time of year (month)',
       'Cardiovascular disease history', 'Dehydration', 'Heat Index (HI)',
       'Diastolic BP', 'Environmental temperature (C)',
       'Sickle Cell Trait (SCT)', 'Systolic BP', 'Weight (kg)',
       'Patient temperature', 'Rectal temperature (deg C)',
       'Relative Humidity', 'Exposure to sun', 'BMI',
       'Exertional (1) vs classic (0)', 'Barometric Pressure',
       'Heart / Pulse rate (b/min)', 'Age', 'Sweating',
       'Skin color (flushed/normal=1, pale=0.5, cyatonic=0)',
       'Strenuous exercise', 'Nationality', 'Sex', 'Hot/dry skin',
       'Time of day', 'Heat stroke'],
      dtype='object')

In [4]:
heat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 609 entries, 0 to 608
Data columns (total 27 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Daily Ingested Water (L)                             609 non-null    float64
 1   Time of year (month)                                 609 non-null    float64
 2   Cardiovascular disease history                       609 non-null    int64
 3   Dehydration                                          609 non-null    int64
 4   Heat Index (HI)                                      609 non-null    float64
 5   Diastolic BP                                         609 non-null    float64
 6   Environmental temperature (C)                        609 non-null    float64
 7   Sickle Cell Trait (SCT)                              609 non-null    int64
 8   Systolic BP                                          609 non-null    float64
 9   Weight (kg)                                          609 non-null    float64
 10  Patient temperature                                  609 non-null    float64
 11  Rectal temperature (deg C)                           609 non-null    float64
 12  Relative Humidity                                    609 non-null    float64
 13  Exposure to sun                                      609 non-null    float64
 14  BMI                                                  609 non-null    float64
 15  Exertional (1) vs classic (0)                        609 non-null    int64
 16  Barometric Pressure                                  609 non-null    float64
 17  Heart / Pulse rate (b/min)                           609 non-null    float64
 18  Age                                                  609 non-null    float64
 19  Sweating                                             609 non-null    int64
 20  Skin color (flushed/normal=1, pale=0.5, cyatonic=0)  609 non-null    float64
 21  Strenuous exercise                                   609 non-null    float64
 22  Nationality                                          609 non-null    int64
 23  Sex                                                  609 non-null    int64
 24  Hot/dry skin                                         609 non-null    int64
 25  Time of day                                          609 non-null    float64
 26  Heat stroke                                          609 non-null    int64
dtypes: float64(18), int64(9)
memory usage: 128.6 KB

In [7]:
heat.describe()

,Daily Ingested Water (L),Time of year (month),Cardiovascular disease history,Dehydration,Heat Index (HI),Diastolic BP,Environmental temperature (C),Sickle Cell Trait (SCT),Systolic BP,Weight (kg),...,Heart / Pulse rate (b/min),Age,Sweating,"Skin color (flushed/normal=1, pale=0.5, cyatonic=0)",Strenuous exercise,Nationality,Sex,Hot/dry skin,Time of day,Heat stroke
count,609.000000,609.000000,609.000000,609.000000,609.000000,609.000000,609.000000,609.000000,609.000000,609.000000,...,609.000000,609.000000,609.000000,609.000000,609.000000,609.000000,609.000000,609.000000,609.000000,609.000000
mean,3.520119,6.091975,0.047619,0.001642,84.497405,81.235813,31.277937,0.003284,114.323615,47.751283,...,120.420787,41.129276,0.441708,0.082874,0.388117,0.563218,0.515599,0.077176,12.819241,0.178982
std,1.443838,3.471044,0.213134,0.040522,16.266051,13.365608,5.706509,0.057260,15.319954,5.548351,...,27.761283,14.501809,0.496999,0.182378,0.292983,0.496395,0.500167,0.267089,2.270532,0.383652
min,1.005512,0.003924,0.000000,0.000000,31.859605,0.000000,14.133432,0.000000,0.000000,41.279030,...,41.647529,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.002272,0.000000
25%,2.335941,3.003778,0.000000,0.000000,73.005260,81.388233,27.459657,0.000000,111.899424,44.442865,...,102.851595,28.676784,0.000000,0.023166,0.111133,0.000000,0.000000,0.000000,10.928394,0.000000
50%,3.501037,6.440839,0.000000,0.000000,83.461479,84.166226,31.157351,0.000000,114.590011,47.647350,...,121.439809,40.462594,0.000000,0.049303,0.377109,1.000000,1.000000,0.000000,12.773230,0.000000
75%,4.749776,9.051857,0.000000,0.000000,98.687987,87.080987,35.509664,0.000000,117.393279,50.594373,...,136.587402,51.379236,1.000000,0.073178,0.639184,1.000000,1.000000,0.000000,14.657338,0.000000
max,10.500000,11.977820,1.000000,1.000000,122.749205,116.000000,44.271485,1.000000,219.000000,151.953000,...,210.290132,90.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,17.000000,1.000000

In [8]:
heat.isna().sum()

Daily Ingested Water (L)                               0
Time of year (month)                                   0
Cardiovascular disease history                         0
Dehydration                                            0
Heat Index (HI)                                        0
Diastolic BP                                           0
Environmental temperature (C)                          0
Sickle Cell Trait (SCT)                                0
Systolic BP                                            0
Weight (kg)                                            0
Patient temperature                                    0
Rectal temperature (deg C)                             0
Relative Humidity                                      0
Exposure to sun                                        0
BMI                                                    0
Exertional (1) vs classic (0)                          0
Barometric Pressure                                    0
Heart / Pulse rate (b/min)                             0
Age                                                    0
Sweating                                               0
Skin color (flushed/normal=1, pale=0.5, cyatonic=0)    0
Strenuous exercise                                     0
Nationality                                            0
Sex                                                    0
Hot/dry skin                                           0
Time of day                                            0
Heat stroke                                            0
dtype: int64

In [17]:
heat['Heat stroke'].value_counts()

0    500
1    109
Name: Heat stroke, dtype: int64

In [13]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler, normalize
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, r2_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn import metrics
from sklearn import tree
from sklearn.tree import DecisionTreeRegressor
import pickle
import yaml

In [6]:
train, test = train_test_split(heat)

In [7]:
train.to_csv('../data/train_heat.csv')

In [8]:
test.to_csv('../data/test_heat.csv')

In [9]:
X = train.drop(["Heat stroke"], axis=1)
y = train["Heat stroke"]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=21)

RANDOM FOREST CLASSIFIER

In [11]:
rf = RandomForestClassifier(n_estimators= 100, random_state=21)
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=21)

In [12]:
pred_rf = rf.predict(X_test)
print(classification_report(y_test, pred_rf, zero_division=1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        75
           1       1.00      1.00      1.00        17

    accuracy                           1.00        92
   macro avg       1.00      1.00      1.00        92
weighted avg       1.00      1.00      1.00        92

LOGISTIC REGRESSION

In [14]:
logisticRegression = LogisticRegression(solver='liblinear')
logisticRegression.fit(X_train, y_train)

LogisticRegression(solver='liblinear')

In [15]:
logreg_score = logisticRegression.score(X_test, y_test)
logreg_score

1.0

In [16]:
pred_logreg = logisticRegression.predict(X_test)
print(classification_report(y_test, pred_logreg, zero_division=1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        75
           1       1.00      1.00      1.00        17

    accuracy                           1.00        92
   macro avg       1.00      1.00      1.00        92
weighted avg       1.00      1.00      1.00        92

In [31]:
# with open('../models/modelo_tree.pkl', 'wb') as modtree:
    # pickle.dump(tree, modtree)

In [32]:
# with open("../models/model_tree.yaml", "w") as a:
#     yaml.dump(tree, a)

RANDOM FOREST REGRESSOR

In [ ]:
# rf = RandomForestRegressor()
# rf.fit(X_train, y_train)
# r2_score(y_test, rf.predict(X_test))

In [34]:
# with open('../models/modelo_tree.pkl', 'rb') as archivo_entrada:
#     modelo_entrenado = pickle.load(archivo_entrada)

**EVALUACIÓN**

In [19]:
heat_test = pd.read_csv('../data/test_heat.csv', index_col=0)
heat_test

,Daily Ingested Water (L),Time of year (month),Cardiovascular disease history,Dehydration,Heat Index (HI),Diastolic BP,Environmental temperature (C),Sickle Cell Trait (SCT),Systolic BP,Weight (kg),...,Heart / Pulse rate (b/min),Age,Sweating,"Skin color (flushed/normal=1, pale=0.5, cyatonic=0)",Strenuous exercise,Nationality,Sex,Hot/dry skin,Time of day,Heat stroke
542,3.056915,4.386062,0,0,98.201863,83.036677,23.943873,0,115.335919,45.662323,...,132.551330,55.755494,1,0.085838,0.430180,0,1,0,10.573556,0
465,4.994865,4.723944,0,0,63.020308,82.409870,35.521797,0,113.853153,53.123099,...,53.073766,18.615005,0,0.053404,0.802746,0,0,0,10.195179,0
482,5.337335,8.788509,0,0,94.618263,83.543997,32.143209,0,115.797183,44.952219,...,126.664333,18.012472,0,0.022296,0.845564,1,0,0,9.807654,0
332,1.363021,11.695114,0,0,109.090924,82.447190,31.024679,0,114.400878,49.113083,...,67.195189,29.066205,0,0.066042,0.075652,1,1,0,14.404816,0
468,2.328718,6.214852,0,0,94.288789,82.394774,26.169362,0,119.208067,48.748253,...,51.590470,48.248327,1,0.054605,0.214929,0,1,0,16.927396,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,2.434377,8.954478,0,0,64.709670,85.474592,26.193651,0,111.336443,48.998246,...,112.950831,41.073253,0,0.022653,0.380849,0,1,0,13.012613,0
430,5.151929,4.259048,0,0,100.759698,83.478808,19.319899,0,116.185626,50.493369,...,146.064579,18.539128,1,0.045556,0.157481,1,0,0,9.635559,0
594,4.914304,6.445933,0,0,108.818283,88.131248,28.319715,0,112.767981,42.931743,...,151.542617,33.226671,0,0.076450,0.690951,1,0,0,12.691231,0
101,5.990881,11.000000,0,0,104.011952,40.000000,36.161724,0,80.000000,46.081935,...,121.492510,55.000000,1,0.018094,0.000000,1,0,0,13.204610,1
84,1.570852,10.603580,0,0,97.742413,70.000000,39.980249,0,120.000000,48.189096,...,135.000000,60.000000,0,0.057588,0.000000,1,0,1,11.745724,1

In [21]:
X_val = heat_test.drop(columns=['Heat stroke'])
X_val

,Daily Ingested Water (L),Time of year (month),Cardiovascular disease history,Dehydration,Heat Index (HI),Diastolic BP,Environmental temperature (C),Sickle Cell Trait (SCT),Systolic BP,Weight (kg),...,Barometric Pressure,Heart / Pulse rate (b/min),Age,Sweating,"Skin color (flushed/normal=1, pale=0.5, cyatonic=0)",Strenuous exercise,Nationality,Sex,Hot/dry skin,Time of day
542,3.056915,4.386062,0,0,98.201863,83.036677,23.943873,0,115.335919,45.662323,...,29.97,132.551330,55.755494,1,0.085838,0.430180,0,1,0,10.573556
465,4.994865,4.723944,0,0,63.020308,82.409870,35.521797,0,113.853153,53.123099,...,29.97,53.073766,18.615005,0,0.053404,0.802746,0,0,0,10.195179
482,5.337335,8.788509,0,0,94.618263,83.543997,32.143209,0,115.797183,44.952219,...,29.97,126.664333,18.012472,0,0.022296,0.845564,1,0,0,9.807654
332,1.363021,11.695114,0,0,109.090924,82.447190,31.024679,0,114.400878,49.113083,...,29.97,67.195189,29.066205,0,0.066042,0.075652,1,1,0,14.404816
468,2.328718,6.214852,0,0,94.288789,82.394774,26.169362,0,119.208067,48.748253,...,29.97,51.590470,48.248327,1,0.054605,0.214929,0,1,0,16.927396
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,2.434377,8.954478,0,0,64.709670,85.474592,26.193651,0,111.336443,48.998246,...,29.97,112.950831,41.073253,0,0.022653,0.380849,0,1,0,13.012613
430,5.151929,4.259048,0,0,100.759698,83.478808,19.319899,0,116.185626,50.493369,...,29.97,146.064579,18.539128,1,0.045556,0.157481,1,0,0,9.635559
594,4.914304,6.445933,0,0,108.818283,88.131248,28.319715,0,112.767981,42.931743,...,29.97,151.542617,33.226671,0,0.076450,0.690951,1,0,0,12.691231
101,5.990881,11.000000,0,0,104.011952,40.000000,36.161724,0,80.000000,46.081935,...,29.97,121.492510,55.000000,1,0.018094,0.000000,1,0,0,13.204610
84,1.570852,10.603580,0,0,97.742413,70.000000,39.980249,0,120.000000,48.189096,...,29.97,135.000000,60.000000,0,0.057588,0.000000,1,0,1,11.745724

In [22]:
y_val = heat_test['Heat stroke']

In [38]:
# X_train, X_test, y_train, y_test = train_test_split(X_val, y_val, test_size=0.20, random_state=21)

In [39]:
# predicciones = modelo_entrenado.predict(X_test)
# modelo_entrenado.score(X_test, y_test)

0.8914150093901105